### ISSUE TITLE
norms not mapped correctly

### ISSUE THREAD

**Issue by ymnliu** [OHNLP/ohnlptk#3]
@hehuan2112  
Please see the unexpected behavior in the screenshot. The norms are not mapped to the correct ones. Here all are mapped to `VIVIDDREAMS` but it should not the case. Can you look into the cause?
![Screenshot 2021-03-18 131511](https://user-images.githubusercontent.com/6431346/111676497-39ff5b00-87ec-11eb-9e73-ae3940b98f9e.png)

**Comment by hehuan2112** [comment]
Sure

**Comment by ymnliu** [comment]
It is fixed. Thanks!
